### PR TITLE
port deprecated function and fix import

### PR DESCRIPTION
**Pull request by yoshrote**
not sure if there will be more work to do yet.

### CODE REVIEW

**Comment by slinkp** [comment]
Looks OK. Would feel better if we had CI running for our fork

**Comment by slinkp** [comment]
👋 @cullenbmacdonald

**Comment by joshkehn** [comment]
seemslegit3 for sure.

**Comment by matthewstory** [comment]
Margo wins this thread.

**Comment by surbas** [comment]
Yeah is she the ci bot?

**Pull request merged**
